Update BatchIndex.java
Because of unknown reason, the /lib/scanner folder was not extracted from the windows archive several times on our server.
/batch/index fails without notifying the user.
The SonarQube Azure DevOps task will fail with a cryptic error :
##[error]ERROR: Failed bootstrap index response:
ERROR: Failed bootstrap index response: